config/routes.rb
Rails.application.routes.draw do
  get '/analyze_query/:id', to: 'image_queries#analyze_query', as: 'analyze_query'
  resources :image_queries
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/image_query.rb
class ImageQuery < ApplicationRecord
  belongs_to :person
  has_one_attached :image
end

app/controllers/image_queries_controller.rb
class ImageQueriesController < ApplicationController
  before_action :set_image_query, only: %i[ analyze_query show edit update destroy ]

  # GET /image_queries or /image_queries.json
  def index
    @image_queries = ImageQuery.all.with_attached_image
  end

  # GET /image_queries/1 or /image_queries/1.json
  def show
  end

  # GET /image_queries/new
  def new
    @image_query = ImageQuery.new
  end

  # GET /image_queries/1/edit
  def edit
  end

  def analyze_query
    result = ImageQueriesHelper::QueryImages.new(@image_query).run

    respond_to do |format|
      if result
        format.html { redirect_to @image_query, notice: "Image query results are in!" }
        format.json { render :show, status: :created, location: @image_query }
      else
        format.html { redirect_to @image_query, notice: "Could not process query. Try again." }
        format.json { render :show, status: :unprocessable_entity, location: @image_query }
      end
    end
  end

  # POST /image_queries or /image_queries.json
  def create
    @image_query = ImageQuery.new(image_query_params)

    respond_to do |format|
      if @image_query.save
        format.html { redirect_to @image_query, notice: "Image query was successfully created." }
        format.json { render :show, status: :created, location: @image_query }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_queries/1 or /image_queries/1.json
  def update
    respond_to do |format|
      if @image_query.update(image_query_params)
        format.html { redirect_to @image_query, notice: "Image query was successfully updated." }
        format.json { render :show, status: :ok, location: @image_query }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_queries/1 or /image_queries/1.json
  def destroy
    @image_query.destroy
    respond_to do |format|
      format.html { redirect_to image_queries_url, notice: "Image query was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_query
      @image_query = ImageQuery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_query_params
      params.require(:image_query).permit(:name, :person_id, :is_match, :percentage_match, :image, :meta)
    end
end

app/helpers/image_queries_helper.rb
module ImageQueriesHelper
  class AwsRekognitionClient
    def initialize(source_image, target_image)
      @credentials = Aws::Credentials.new(
        ENV['AWS_ACCESS_KEY_ID'],
        ENV['AWS_SECRET_ACCESS_KEY']
      )

      @source_image = source_image
      @target_image = target_image
    end

    def matches
      @matches ||= compare.face_matches
    end

    def detected
      @detected||= detect.face_details
    end

    def matches_to_s
      matches.each do |face_match|
        position   = face_match.face.bounding_box
        similarity = face_match.similarity
        puts "The face at: #{position.left}, #{position.top} matches with #{similarity} % confidence"
      end
    end

    def detected_to_s
      detected.each do |face_detail|
        low  = face_detail.age_range.low
        high = face_detail.age_range.high
        puts "The detected face is between: #{low} and #{high} years old"
        puts "All other attributes:"
        puts "  bounding_box.width:     #{face_detail.bounding_box.width}"
        puts "  bounding_box.height:    #{face_detail.bounding_box.height}"
        puts "  bounding_box.left:      #{face_detail.bounding_box.left}"
        puts "  bounding_box.top:       #{face_detail.bounding_box.top}"
        puts "  age.range.low:          #{face_detail.age_range.low}"
        puts "  age.range.high:         #{face_detail.age_range.high}"
        puts "  smile.value:            #{face_detail.smile.value}"
        puts "  smile.confidence:       #{face_detail.smile.confidence}"
        puts "  eyeglasses.value:       #{face_detail.eyeglasses.value}"
        puts "  eyeglasses.confidence:  #{face_detail.eyeglasses.confidence}"
        puts "  sunglasses.value:       #{face_detail.sunglasses.value}"
        puts "  sunglasses.confidence:  #{face_detail.sunglasses.confidence}"
        puts "  gender.value:           #{face_detail.gender.value}"
        puts "  gender.confidence:      #{face_detail.gender.confidence}"
        puts "  beard.value:            #{face_detail.beard.value}"
        puts "  beard.confidence:       #{face_detail.beard.confidence}"
        puts "  mustache.value:         #{face_detail.mustache.value}"
        puts "  mustache.confidence:    #{face_detail.mustache.confidence}"
        puts "  eyes_open.value:        #{face_detail.eyes_open.value}"
        puts "  eyes_open.confidence:   #{face_detail.eyes_open.confidence}"
        puts "  mouth_open.value:       #{face_detail.mouth_open.value}"
        puts "  mouth_open.confidence:  #{face_detail.mouth_open.confidence}"
        puts "  emotions[0].type:       #{face_detail.emotions[0].type}"
        puts "  emotions[0].confidence: #{face_detail.emotions[0].confidence}"
        puts "  landmarks[0].type:      #{face_detail.landmarks[0].type}"
        puts "  landmarks[0].x:         #{face_detail.landmarks[0].x}"
        puts "  landmarks[0].y:         #{face_detail.landmarks[0].y}"
        puts "  pose.roll:              #{face_detail.pose.roll}"
        puts "  pose.yaw:               #{face_detail.pose.yaw}"
        puts "  pose.pitch:             #{face_detail.pose.pitch}"
        puts "  quality.brightness:     #{face_detail.quality.brightness}"
        puts "  quality.sharpness:      #{face_detail.quality.sharpness}"
        puts "  confidence:             #{face_detail.confidence}"
        puts "------------"
        puts ""
      end
    end

    private

    attr_reader :credentials, :source_image, :target_image

    def compare
      @compare ||= client.compare_faces(compare_attrs)
    end

    def detect
      @detect ||= client.detect_faces(detect_attrs)
    end

    def client
      @client ||= Aws::Rekognition::Client.new(credentials: credentials)
    end

    def detect_attrs
      {
        image: {
          bytes: source_image,
        },
        attributes: ['ALL']
      }
    end

    def compare_attrs
      {
        source_image: {
          bytes: source_image,
        },
        target_image: {
          bytes: target_image,
        },
        similarity_threshold: 70
      }
    end
  end

  class QueryImages
    def initialize(image_query)
      @image_query = image_query
    end

    def run
      set_queried_params
      image_query.save
    end

    private

    attr_reader :image_query

    def set_queried_params
      image_query.is_match = queried_is_match
      image_query.percentage_match = queried_percentage_match
      image_query.matches_meta = queried_matches_meta
      image_query.detected_meta = queried_detected_meta
    end

    def queried_is_match
      queried_percentage_match > 90 ? true : false
    end

    def queried_percentage_match
      aws_rekog_client.matches.first.similarity
    end

    def queried_matches_meta
      aws_rekog_client.matches_to_s
    end

    def queried_detected_meta
      aws_rekog_client.detected_to_s
    end

    def aws_rekog_client
      processed_source_image = image_query.image.variant(resize_to_limit: [200, 200]).processed
      processed_target_image = image_query.person.image.variant(resize_to_limit: [200, 200]).processed
      source_image = processed_source_image.download
      target_image = processed_target_image.download
      AwsRekognitionClient.new(source_image, target_image)
    end
  end
end

app/views/image_queries/_form.html.erb
<%= form_with(model: image_query) do |form| %>
  <% if image_query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_query.errors.count, "error") %> prohibited this image_query from being saved:</h2>

      <ul>
        <% image_query.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.text_field :person_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/image_queries/edit.html.erb
<h1>Image Query</h1>

<%= render 'form', image_query: @image_query %>

<%= link_to 'Show', @image_query %> |
<%= link_to 'Back', image_queries_path %>

app/views/image_queries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Queries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Person</th>
      <th>Is match</th>
      <th>Percentage match</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_queries.each do |image_query| %>
      <tr>
        <td><%= image_query.name %></td>
        <td><%= image_query.person.firstname %></td>
        <td><%= image_query.is_match %></td>
        <td><%= image_query.percentage_match %></td>
        <td><%= link_to 'Show', image_query %></td>
        <td><%= link_to 'Edit', edit_image_query_path(image_query) %></td>
        <td><%= link_to 'Destroy', image_query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image Query', new_image_query_path %>

app/views/image_queries/new.html.erb
<h1>Submit Image Query</h1>

<%= render 'form', image_query: @image_query %>

<%= link_to 'Back', image_queries_path %>

app/views/image_queries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image_query.name %>
</p>

<% if @image_query.person.image.attached? %>
  <p>
    <strong>Person Image:</strong>
    <%= image_tag @image_query.person.image.variant(resize_to_limit: [200, 200]) %>
  </p>
<% end %>

<p>
  <strong>Is match:</strong>
  <%= @image_query.is_match %>
</p>

<p>
  <strong>Percentage match:</strong>
  <%= @image_query.percentage_match %>
</p>

<% if @image_query.image.attached? %>
  <p>
    <strong>Image:</strong>
    <%= image_tag @image_query.image.variant(resize_to_limit: [200, 200]) %>
  </p>
<% end %>

<hr>
<h3>Match details</h3>
<p>
  <strong>Data:</strong>
  <%= @image_query.matches_meta %>
</p>
<br><br>
<hr>
<h3>Face detection details</h3>
<p>
  <strong>Data:</strong>
  <%= @image_query.detected_meta %>
</p>

<%= link_to 'Analyze query', analyze_query_path(@image_query) %> |
<%= link_to 'Edit', edit_image_query_path(@image_query) %> |
<%= link_to 'Back', image_queries_path %>